### ISSUE TITLE
counter not set to bold typeface

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#113]
The counter is not set to the bold font. This is visible in ```jasiMasters/JasiMasters2024041401.xml```

<img width="450" alt="SCR-20240528-kcki" src="https://github.com/bartneck/swiML/assets/19443755/d1f13a88-e790-499a-b57b-2764b39aa967">

**Comment by calloc262** [comment]
The XML code for a lot of the recent jasi files aren't present but I tried to recreate the program and came up with this:
![boldexample](https://github.com/bartneck/swiML/assets/119980100/2890791f-a28e-4b96-aa2f-451f05b01fe8)
Not sure why there are 1x there but they probably shouldn't be, although it should be a 1 instead of a 100

**Comment by bartneck** [comment]
The counter font issue has been tested and is okay. There is still another issue, but I will raise this as a separate open issue.
