### ISSUE TITLE
length missing in simplified repetition

### ISSUE THREAD

**Issue by bartneck** [bartneck/swiML#99]
The 50m and 100m are missing from the repetition ```JasiMasters2024032401.xml```

Have a look at the image to see how exactly the 8x150 are to be swum.

![SCR-20240327-kk2](https://github.com/bartneck/swiML/assets/19443755/b9187974-1a71-4aa1-800e-db43d0b17f08)

**Comment by calloc262** [comment]
The XSL is breaking because the way this is represented should cause an XSD assertion failure,
You're representing the 150 as a repetition of a 50 and a 100, which isn't a 150.
So either the inside of each 2x repetition should be wrapped in a continue to make them 150s 
or these are meant to be broken 150s as there is rest after each stop, something that is not currently achievable using the current xsd and xsl.

**Comment by bartneck** [comment]
Okay, this will become a feature request. I will keep this open until we have the time to fix this. Maybe we need to create a new type of repetition that includes required lengths.

**Comment by bartneck** [comment]
I tried this again with a repetition that only consists of 50 meters:
```jasiMasters/JasiMasters2024032601.xml```
<img width="437" alt="SCR-20240524-noed" src="https://github.com/bartneck/swiML/assets/19443755/6d163950-0b12-4856-a842-64b94f2aabd9">
It should be 16 x 50 meters in the front. The 50 meters inside the brackets should be shown. There seems to be something else wrong here. According to your explanation, this should have worked if all the instructions are of the same length.
